# Generated by Django 2.0.1 on 2018-06-19 20:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pricing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('group', models.CharField(choices=[('Mechanical', 'Mechanika'), ('Electrical', 'Elektryka'), ('Pneumatics', 'Pneumatyka')], default=pricing.models.Group('Elektryka'), max_length=30)),
                ('is_component', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ElementRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('leader', models.CharField(max_length=35)),
                ('description', models.TextField()),
            ],
            bases=(models.Model, pricing.models.Relationship),
        ),
        migrations.CreateModel(
            name='ProjectComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pricing.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='component', serialize=False, to='pricing.Element')),
                ('project_name', models.CharField(default='', max_length=30)),
            ],
            bases=('pricing.element', pricing.models.Relationship),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='product', serialize=False, to='pricing.Element')),
                ('brand', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            bases=('pricing.element',),
        ),
        migrations.AddField(
            model_name='elementrelationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Element'),
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('is_component', 'name')},
        ),
        migrations.AddField(
            model_name='projectcomponent',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Component'),
        ),
        migrations.AddField(
            model_name='elementrelationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='pricing.Component'),
        ),
        migrations.AlterUniqueTogether(
            name='elementrelationship',
            unique_together={('parent', 'child')},
        ),
    ]
