# Generated by Django 2.0.1 on 2018-05-26 21:21

from django.db import migrations, models
import django.db.models.deletion
import pricing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('group', models.IntegerField(choices=[('Mechanical', 0), ('Electrical', 1)], default=pricing.models.Group(1))),
            ],
        ),
        migrations.CreateModel(
            name='ElementRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='component', serialize=False, to='pricing.Element')),
                ('project_name', models.CharField(default='', max_length=30)),
            ],
            bases=('pricing.element',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='product', serialize=False, to='pricing.Element')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            bases=('pricing.element',),
        ),
        migrations.AddField(
            model_name='elementrelationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Element'),
        ),
        migrations.AddField(
            model_name='elementrelationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='pricing.Component'),
        ),
        migrations.AlterUniqueTogether(
            name='elementrelationship',
            unique_together={('parent', 'child')},
        ),
    ]
