# Generated by Django 2.0.1 on 2018-05-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_component',
            field=models.BooleanField(default=True),
        ),
    ]
