# Generated by Django 2.0.1 on 2018-05-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_element_is_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='is_component',
            field=models.BooleanField(),
        ),
    ]
