# Generated by Django 2.0.1 on 2018-06-15 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pricing.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20180527_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('leader', models.CharField(max_length=35)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Component')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pricing.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='element',
            name='group',
            field=models.IntegerField(choices=[(0, 'Mechanical'), (1, 'Electrical')], default=pricing.models.Group(1)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('is_component', 'name')},
        ),
    ]
